name: Data Processing

on:
  push:
    branches:
      - main

jobs:
  process_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install pandas
          pip install kaggle

      - name: Set up Kaggle credentials
        run: |
          mkdir -p ~/.kaggle
          echo "${{ secrets.KAGGLE_KEY }}" > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json

      - name: Download dataset from Kaggle
        run: |
          kaggle datasets download -d akshatgupta7/crop-yield-in-indian-states-dataset
          unzip crop-yield-in-indian-states-dataset.zip

      - name: Run preprocessing script
        run: |
          python BronzeLayer.py
