name: Generate Bronze Layer Data

on:
  push:
    paths:
      - BronzeLayer.py
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-22.04

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      # Step 3: Install dependencies
      - name: Install Python dependencies
        run: |
          pip install pandas numpy matplotlib seaborn kaggle

      # Step 4: Configure Kaggle credentials
      - name: Configure Kaggle credentials
        run: |
          mkdir -p ~/.kaggle
          echo "${{ secrets.KAGGLE_KEY }}" > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json

      # Step 5: Run Bronze Layer script
      - name: Run Bronze Layer script
        run: |
          python BronzeLayer.py

      # Step 6: Commit and Push BronzeLayer_data.csv
      - name: Commit and Push BronzeLayer_data.csv
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add BronzeLayer_data.csv
          git commit -m "Update BronzeLayer_data.csv [Automated]"
          git push
